# Generated by Django 4.0.6 on 2022-08-31 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone_num',
            field=models.CharField(max_length=8),
        ),
    ]
