# Generated by Django 4.0.6 on 2022-08-31 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0002_alter_register_phone_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='carnet',
            new_name='Carnet',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='career',
            new_name='Carrera',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='direction',
            new_name='Direction',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='date',
            new_name='Fecha',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='gender',
            new_name='Genero',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='date_birth',
            new_name='Nacimiento',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='full_name',
            new_name='NombreCompleto',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='phone_num',
            new_name='Numero',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='tpoetry',
            new_name='TipoPoesia',
        ),
    ]
